name: BT Onsite
favicon: null
layout_spectrum: 0.25027
typography_spectrum: 0.75931
title: Body Techniques Corporate Onsite Wellness Suite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e51b24'
    - '#000000'
    - '#ffffff'
    - '#f7bcbf'
    - '#ee6c72'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
