name: BT Onsite
favicon: null
layout_spectrum: 0.5376983031164855
typography_spectrum: 0.3726471692789346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.30722292652353644
  lightness: 0.9433564585633576
  saturation: 0.8126853546127677
  rhythmicContrast: 0.4214124034624547
purpose: []
