name: BT Onsite
favicon: null
layout_spectrum: 0.5376983031164855
typography_spectrum: 0.3726471692789346
title: Body Techniques Corporate Onsite Wellness Suite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e51b24'
    - '#000000'
    - '#ffffff'
    - '#f7bcbf'
    - '#ee6c72'
  brandStrength: 1
  lightness: 0.9433564585633576
  saturation: 0.8126853546127677
  rhythmicContrast: 0.4214124034624547
purpose: []
